# -*- coding: UTF-8 -*-
from wsdm_digg.benchmark.evaluator import *
from wsdm_digg.constants import *

# print(Evaluator().evaluation_map(RESULT_DIR + 'baseline.jsonl'))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'cite_textrank_top15.jsonl', top_n=10))
# print(Evaluator().evaluation_map(RESULT_DIR + 'more_keywords.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'singlerank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'singlerank_on_cites.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'weighted_textrank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'weighted_textrank_w_3.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_top10.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_textrank_top10.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_textrank_top15.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_textrank_top15_TA.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_textrank_top15_TA_weight5.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_textrank_top15_TA_weight10.jsonl'))
print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA_vector_rerank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'TA_text_noun_chunk.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'TA_textrank_text_10_cites_20.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'TA_text_textrank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'text_noun_chunk.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'weight_t3_a5.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'weight_t3_a5_k1.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'cite_keywords_w2.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'query_word_lemma.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'query_terms_dedupe.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'text_singlerank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'text_textrank_binary_top5.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_join_keyword.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_join_keyword_t10_c15.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_t10_c15.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_t_window3_c_window3.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA_prf.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA_prf_2.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA_copyrnn.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'textrank_t10_c10.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'no_text_textrank.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'noun_chunk_lemma.jsonl'))
# print(Evaluator().evaluation_map(RESULT_DIR + 'paper_keywords_oracle.jsonl'))
# print(Evaluator().evaluation_map(RERANK_RESULT_DIR + 'only_TA_rerank_scheduler_step_40000_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_conv-knrm_rerank_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_desc_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top15_rerank_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_norm_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_step_10000_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_norm_conv-krnm_top10.jsonl'))
# print(Evaluator().evaluation_map(
#     DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_norm_conv-krnm_step_30000_top10.jsonl'))
# print(Evaluator().evaluation_map(
#     DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_norm_conv-krnm_step_20000_top10.jsonl'))
# print(Evaluator().evaluation_map(
#     DATA_DIR + 'rerank_result/cite_textrank_top15_rerank_norm_conv-krnm_step_20000_top10.jsonl'))
# print(Evaluator().evaluation_map(
#     DATA_DIR + 'rerank_result/cite_textrank_top15_rerank_norm_conv-krnm_step_40000_top10.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_top20.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_top50.jsonl'))
# print(Evaluator().evaluation_map(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_top100.jsonl'))
# print(Evaluator().evaluation_recall(DATA_DIR + 'rerank_result/cite_textrank_top10_rerank_top100.jsonl',
#                                     top_n=100))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'no_text_textrank.jsonl', top_n=50))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'only_TA.jsonl', top_n=100))
# print(Evaluator().evaluation_map(RESULT_DIR + 'only_TA_vector_rerank_top100.jsonl'))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'only_TA_vector_rerank_top500.jsonl', top_n=20))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'only_TA_vector_rerank_top100.jsonl', top_n=20))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'only_TA_vector_rerank_top60.jsonl', top_n=20))
# print(Evaluator().evaluation_recall(RESULT_DIR + 'only_TA_vector_rerank_top200.jsonl', top_n=20))

